name: 'Terraform Azure Deployment'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Extract Azure Service Principal credentials
      id: extract-sp
      run: |
        echo "::set-output name=subscription_id::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.subscriptionId')"
        echo "::set-output name=tenant_id::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.tenantId')"
        echo "::set-output name=client_id::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId')"
        echo "::set-output name=client_secret::$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientSecret')"

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="subscription_id=${{ steps.extract-sp.outputs.subscription_id }}" \
          -backend-config="tenant_id=${{ steps.extract-sp.outputs.tenant_id }}" \
          -backend-config="client_id=${{ steps.extract-sp.outputs.client_id }}" \
          -backend-config="client_secret=${{ steps.extract-sp.outputs.client_secret }}"
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
      
    # Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      run: |
        ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)
        az acr login --name $(echo $ACR_LOGIN_SERVER | cut -d'.' -f1)
      working-directory: ./terraform
      
    # Build and push Docker image
    - name: Build and push Docker image
      run: |
        ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)
        docker build -t $ACR_LOGIN_SERVER/imgralfr3v2uat:latest .
        docker push $ACR_LOGIN_SERVER/imgralfr3v2uat:latest
      working-directory: ./